#!/usr/bin/env node
// Commit message policy for Stellarr (see AGENTS.md "Git workflow").
//
//   commit-msg.mjs <message-file>     check one message (git commit-msg hook)
//   commit-msg.mjs --range <a..b>     check every non-merge commit in a range
//   commit-msg.mjs --self-test        prove the checker accepts and rejects
//
// Rules: Conventional Commits subject, subject at most 72 characters, no AI
// attribution trailers, no emoji. Merge, revert, fixup! and squash! subjects
// generated by git are accepted. Dependabot commits are skipped in range mode
// because their subjects are generated (and replaced by the PR title on
// squash merge).

import { execFileSync } from 'node:child_process';
import { readFileSync } from 'node:fs';

const TYPES = 'feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert';
const CONVENTIONAL = new RegExp(`^(${TYPES})(\\([\\w./-]+\\))?!?: \\S`);
const GIT_GENERATED = /^(Merge |Revert "|fixup! |squash! |amend! )/;
const ATTRIBUTION = [/^co-authored-by:/im, /generated with \[?claude/i, /generated (with|by) (codex|chatgpt|copilot)/i];
const EMOJI = /\p{Extended_Pictographic}/u;
const MAX_SUBJECT = 72;

/** Returns a list of problems; empty means the message passes. */
export function checkMessage(raw) {
  // Drop git's comment lines and everything below a verbose-commit scissors line.
  const body = raw.split('\n# ------------------------ >8 ------------------------')[0];
  const lines = body.split('\n').filter((l) => !l.startsWith('#'));
  const text = lines.join('\n').trim();
  const subject = text.split('\n')[0] ?? '';
  const problems = [];

  if (!subject) return ['empty commit message'];
  if (!GIT_GENERATED.test(subject) && !CONVENTIONAL.test(subject)) {
    problems.push(`subject is not a Conventional Commit ("<type>[(scope)][!]: <description>", types: ${TYPES.replaceAll('|', ', ')})`);
  }
  if ([...subject].length > MAX_SUBJECT) {
    problems.push(`subject is ${[...subject].length} characters; keep it at most ${MAX_SUBJECT}`);
  }
  for (const pattern of ATTRIBUTION) {
    if (pattern.test(text)) problems.push(`AI attribution is not allowed (matched ${pattern})`);
  }
  if (EMOJI.test(text)) problems.push('emoji are not allowed in commit messages');
  return problems;
}

function checkRange(range) {
  const log = execFileSync('git', ['log', '--format=%H%x1f%P%x1f%ae%x1f%B%x1e', range], { encoding: 'utf8' });
  let failures = 0;
  for (const entry of log.split('\x1e')) {
    const [hash, parents, email, message] = entry.replace(/^\n/, '').split('\x1f');
    if (!hash) continue;
    if (parents.trim().split(' ').length > 1) continue; // merge commit
    if (email.includes('dependabot[bot]')) continue;
    const problems = checkMessage(message);
    if (problems.length) {
      failures++;
      console.error(`${hash.slice(0, 7)} ${message.split('\n')[0]}`);
      for (const p of problems) console.error(`  - ${p}`);
    }
  }
  if (failures) {
    console.error(`\n${failures} commit message(s) in ${range} break the policy in AGENTS.md (reword with git rebase -i).`);
    return 1;
  }
  console.log(`commit-msg: all commits in ${range} pass`);
  return 0;
}

function selfTest() {
  const pass = [
    'feat: add MIDI learn to parameter knobs',
    'fix(bridge): harden inbound event boundary (#205)',
    'feat!: drop legacy preset format',
    'chore(deps-dev): bump vitest to 5',
    'Merge branch \'main\' into feature/x',
    'Revert "feat: add thing"',
    'docs: update manual\n\n# Please enter the commit message\n# Co-Authored-By: commented out by git',
  ];
  const fail = [
    ['add a thing', 'Conventional'],
    ['feature: add a thing', 'Conventional'],
    ['feat:missing space', 'Conventional'],
    ['fix: ' + 'x'.repeat(70), 'characters'],
    ['fix: thing\n\nCo-Authored-By: Claude <noreply@anthropic.com>', 'attribution'],
    ['fix: thing\n\nGenerated with [Claude Code](https://claude.com/claude-code)', 'attribution'],
    ['fix: ship it \u{1F680}', 'emoji'],
    ['', 'empty'],
  ];
  let bad = 0;
  for (const msg of pass) {
    const p = checkMessage(msg);
    if (p.length) { bad++; console.error(`self-test: expected PASS for ${JSON.stringify(msg)}, got ${p.join('; ')}`); }
  }
  for (const [msg, expect] of fail) {
    const p = checkMessage(msg);
    if (!p.some((x) => x.includes(expect))) { bad++; console.error(`self-test: expected FAIL (${expect}) for ${JSON.stringify(msg)}, got ${JSON.stringify(p)}`); }
  }
  if (bad) return 1;
  console.log(`commit-msg: self-test passed (${pass.length} accepted, ${fail.length} rejected)`);
  return 0;
}

const [arg, value] = process.argv.slice(2);
if (arg === '--self-test') process.exit(selfTest());
if (arg === '--range' && value) process.exit(checkRange(value));
if (arg && !arg.startsWith('--')) {
  const problems = checkMessage(readFileSync(arg, 'utf8'));
  if (problems.length) {
    console.error('Commit message rejected (see AGENTS.md "Git workflow"):');
    for (const p of problems) console.error(`  - ${p}`);
    process.exit(1);
  }
  process.exit(0);
}
console.error('usage: commit-msg.mjs <message-file> | --range <a..b> | --self-test');
process.exit(2);
